# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      with:
        config-path: .gitleaks.toml

  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: main
        VALIDATE_ARM: true
        #VALIDATE_JSON: true
        VALIDATE_YAML: true
        VALIDATE_POWERSHELL: true
        VALIDATE_MD: true

  build:
    needs: [gitleaks,linter]
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Infrastructure
        run: sudo pwsh -command "./Deploy-Infra.ps1"

  infrastructure-pester-tests:
    needs: [gitleaks,build,linter]
    name: Run Pester and upload results
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v2
    - name: Test with Pester
      shell: pwsh
      run: sudo pwsh -command "./Run-PesterTests.ps1"
        
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Infra-Tests-Results
        path: testResults.xml
      if: always()
